### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by blutz** [dailybruin/march-madness-bracket#1]
Make a permalink for each user. The user should be able to distribute this link so people can see his/her bracket but cannot edit it. I'm not sure how easy this would be but it's an important feature.

Each user would only get one link (something like `march-madness/?bracket=325` where `352` is the UID we store, _not_ the facebook UID).

**Comment by blutz** [comment]
I can probably do this late tomorrow night but if we could get it done earlier it'd be nice!

**Comment by danielduan** [comment]
would that be a javascript thing or a php thing?

**Comment by thecalvinchan** [comment]
php

**Comment by thecalvinchan** [comment]
So how far are we to completion?

**Comment by blutz** [comment]
Pretty close; I'm finishing stuff up

**Comment by thecalvinchan** [comment]
And once again it's 5 am... Haha, okay let me know if there's anything I
can help with...
